version: "3.8"
services:
  research:
    container_name: research
    build:
      context: ./
      dockerfile: Dockerfile_research
    runtime: nvidia
    environment:
      - PYTHONPATH=/opt/project/
      - BASE_WORKDIR=/opt/project/
      - BASE_OUTPUT_WORKDIR=/opt/project/data/prc/outputs
    ports:
      - "5152:5151"
    volumes:
      - ./data:/opt/project/data
      - .:/opt/project/
    networks:
      - default_network
  
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    volumes:
      - ./app:/opt/project/app
    networks:
      - default_network

networks:
  default_network:
    name: default_network
    driver: bridge
