from enum import StrEnum

class ErrorCode(StrEnum):
    
    INVALID_IMAGE_ERROR = "INVALID_IMAGE_ERROR"
    MULTIPLE_DOCUMENTS_ERROR = "MULTIPLE_DOCUMENTS_ERROR"
    UNKNOWN_CLASS_ERROR = "UNKNOWN_CLASS_ERROR"
    DOCUMENT_NOT_FOUND_ERROR = "DOCUMENT_NOT_FOUND_ERROR"
    SAME_SIDE_ERROR = "SAME_SIDE_ERROR"
    NOT_MATCH_SIDE_ERROR = "NOT_MATCH_SIDE_ERROR"